# Generated by Django 3.2.25 on 2025-03-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="token",
            field=models.CharField(
                default="null", max_length=100, verbose_name="Токен платежа"
            ),
            preserve_default=False,
        ),
    ]
