# Generated by Django 3.2.25 on 2025-03-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_payment", "0002_payment_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создан", "Создан"),
                    ("Подтвержден", "Подтвержден"),
                    ("Отклонен", "Отклонен"),
                    ("Завершен", "Завершен"),
                ],
                default="Создан",
                max_length=100,
                verbose_name="Статус",
            ),
        ),
    ]
